### PR TITLE
Add missing options

### PR DESCRIPTION
**Pull request by pillarsdotnet**
Several fixes:
* [Fix error in `30_bottom.j2`.](https://github.com/willshersystems/ansible-sshd/pull/87/commits/8a2dbf0f41d62b2f596f355424271f359c912caf)
* [Run tests in color.](https://github.com/willshersystems/ansible-sshd/pull/87/commits/275c9afcd41fefcb42864f0e5fe592171f774094)
* [Ensure ansible version is 2.0 or greater.](https://github.com/willshersystems/ansible-sshd/pull/87/commits/2973943f720468c87da1e65c1accd95a00c188d3).
* [Install packages via distro-dependent methods.](https://github.com/willshersystems/ansible-sshd/pull/87/commits/b3a9627e7f53029b1db4863fee4bf5a1c7fd387f)
* [Add missing `options_body` entries](https://github.com/willshersystems/ansible-sshd/pull/87/commits/2a081022d2977cdf67dd251010ef62fb80cb76eb):
  * `AllowStreamLocalForwarding`
  * `AuthorizedPrincipalsCommand`
  * `AuthorizedPrincipalsCommandUser`
  * `DisableForwarding`
  * `ExposeAuthInfo`
  * `FingerprintHash`
  * `GatewayPorts`
  * `HostKeyAlgorithms`
  * `HostbasedAcceptedKeyTypes`
  * `PermitUserRC`
  * `PubkeyAcceptedKeyTypes`
  * `RDomain`
  * `StreamLocalBindMask`
* [Add missing `options_match` entries](https://github.com/willshersystems/ansible-sshd/pull/87/commits/f6dbb91023c1bbd1404a814b77f4cf1a24c680da)
  * `AcceptEnv`
  * `AllowStreamLocalForwarding`
  * `AuthorizedPrincipalsCommand`
  * `AuthorizedPrincipalsCommandUser`
  * `ClientAliveCountMax`
  * `ClientAliveInterval`
  * `HostbasedAcceptedKeyTypes`
  * `IPQoS`
  * `LogLevel`
  * `PermitTTY`
  * `PermitUserRC`
  * `PubkeyAcceptedKeyTypes`
  * `RDomain`
  * `RekeyLimit`
  * `RevokedKeys`
  * `StreamLocalBindMask`
  * `StreamLocalBindUnlink`
  * `TrustedUserCAKeys` (See also #83)

### CODE REVIEW

**Comment by pillarsdotnet** [comment]
@mattwillsher ?

**Comment by mattwillsher** [comment]
Yes I’ve seen the commits. 

I will review in the coming days.

As long as the tests cover both scalar and list variables and both pass then the change will be accepted. 

As I’ve previously said, this change is a change from the original design and must not cause regressions.

**Comment by pillarsdotnet** [comment]
This PR has no functional change; it only adds some options that are available in newer sshd versions.  I need to write tests for the additional changes in #85 though.

**Comment by mattwillsher** [comment]
I'm unclear on b3a9627 - package is used which is distro independent. 

Otherwise this looks good.

**Comment by pillarsdotnet** [comment]
@mattwillsher -- I'll yank that commit.  I had put it in because the travis-ci tester said there was no "package" module.  And there wasn't, in the ansible version 1.3 that it was running...

**Comment by mattwillsher** [comment]
Thanks. TGTM.

**Pull request merged**
