### PR TITLE
add parameter RSAMinSize

### PR DESCRIPTION
**Pull request by richm**
Add support for the new RSAMinSize parameter.

### CODE REVIEW

**Comment by richm** [comment]
Can this be merged?

**Comment by Jakuje** [comment]
For the reference, this option comes from djmdjm/openssh-wip/pull/13 referenced from openssh/openssh-portable/pull/325

**Review by Jakuje — APPROVED** [review]

**Comment by mattwillsher** [comment]
No Changelog/release ?

**Comment by richm** [comment]
> No Changelog/release ?

I will create and submit a PR for the Changelog (there's also an update needed for https://github.com/willshersystems/ansible-sshd/blob/master/.github/workflows/changelog_to_tag.yml)

**Comment by richm** [comment]
> > No Changelog/release ?
> 
> I will create and submit a PR for the Changelog (there's also an update needed for https://github.com/willshersystems/ansible-sshd/blob/master/.github/workflows/changelog_to_tag.yml)

There was no updated needed to changelog_to_tag.yml

https://github.com/willshersystems/ansible-sshd/pull/195

**Comment by richm** [comment]
@Jakuje @mattwillsher I think this PR was incomplete - Should RSAMinSize be in both meta/options_body and meta/options_match?  Should there be an RSAMinSize here - https://github.com/willshersystems/ansible-sshd/blob/master/templates/sshd_config.j2#L92 and here - https://github.com/willshersystems/ansible-sshd/blob/master/templates/sshd_config_snippet.j2#L92 ?

**Comment by Jakuje** [comment]
> @Jakuje @mattwillsher I think this PR was incomplete - Should RSAMinSize be in both meta/options_body and meta/options_match? Should there be an RSAMinSize here - https://github.com/willshersystems/ansible-sshd/blob/master/templates/sshd_config.j2#L92 and here - https://github.com/willshersystems/ansible-sshd/blob/master/templates/sshd_config_snippet.j2#L92 ?

oh, right. It needs to be in both places as the current implementation in openssh allows setting it in the match blocks if I read correctly.

**Comment by richm** [comment]
> > @Jakuje @mattwillsher I think this PR was incomplete - Should RSAMinSize be in both meta/options_body and meta/options_match? Should there be an RSAMinSize here - https://github.com/willshersystems/ansible-sshd/blob/master/templates/sshd_config.j2#L92 and here - https://github.com/willshersystems/ansible-sshd/blob/master/templates/sshd_config_snippet.j2#L92 ?
> 
> oh, right. It needs to be in both places as the current implementation in openssh allows setting it in the match blocks if I read correctly.

ok - I'll submit another PR

**Pull request merged**
