### PR TITLE
Run CI also on Alpine

### PR DESCRIPTION
**Pull request by Jakuje**
Follow-up from #212

### CODE REVIEW

**Comment by Jakuje** [comment]
@findmyname666 @mattwillsher can you have a look?

**Comment by findmyname666** [comment]
Looks good to me, thx.

**Review by mattwillsher — APPROVED** [review]
Nice, thanks.

**Comment by findmyname666** [comment]
Can somebody restart the build for **Run Ansible Check on Ubuntu**  pls?

There was some issue with Ubuntu mirrors today:

```
  W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy/InRelease  Could not connect to archive.ubuntu.com:80 (185.125.190.39), connection timed out Could not connect to archive.ubuntu.com:80 (185.125.190.36), connection timed out
```

BTW does anybody know when new module version will be published so it can be picked up by ansible tooling ?

**Comment by Jakuje** [comment]
Just reran the jobs. Hope it will be better now.

**Comment by Jakuje** [comment]
for the release, I dont have any specific stuff to work on right now, so I think we should be able to release after we will merge this. Lets see if ubuntu will behave now.

**Pull request merged**
