### PR TITLE
Feature add: generate host keys with ssh-keygen

### PR DESCRIPTION
**Pull request by johanfleury**
This commit adds two variables that manage the generation or regeneration of SSH host keys.

### CODE REVIEW

**Comment by mattwillsher** [comment]
Hi Johan,

I like the idea of being able to regenerate the host keys. 

In my experience, at least for EL and Debian based distros, the sshd startup script generates the SSH host keys. 

It's my understanding that after keys are generated sshd will need to be reloaded/restarted to pick up the change.

Given these, I think the default action for regenerate should be to delete the keys via a call to a suitable module and call the reload/restart handler. The regeneration of the keys via ssh-keygen can be done iff a force generation boolean is set. 

Does this make sense and in line with your aims here?

**Comment by Anthony25** [comment]
Hello @mattwillsher,
I worked with @johanfleury on this.

> @mattwillsher:
> Given these, I think the default action for regenerate should be to delete the keys via a call to a suitable module and call the reload/restart handler.

I did not understand what you mean by "a suitable module". You mean writing a module to replace the `shell` directive ?

**Comment by mattwillsher** [comment]
Hi Anthony,

Thanks for getting back to this PR, I appreciate your contribution. I was considering incorporating the refinements myself, but it's your idea and it's good to see others shape the role.

Yes, I mean something other than shell - where there is a module that can perform a given action I like to use that rather than shell out. From memory I think this was a file delete? ( I'm on my phone so can't check right now) in which case the file module will do it, I think. 

It'd be also helpful to get some checks in the travis build configuration, but that definitely a stretch goal :)

If you need any assistance in getting this PR over the line please ask. Once it's ready I'll get it merged and a new version up on Galaxy.

**Comment by Anthony25** [comment]
Ok, I see. A problem here is that file does not handle wildcards, so we cannot write:
```
file: dest="/etc/ssh/ssh_host_*" state=absent
```
That means we have to manually declare each hostkey if we still want to use `file`, which is (in my opinion) less permissive to future changes done in ssh, compared to `ssh-keygen -A` (the hostkey list will need to be up-to-date).
Using the workaround `shell: "rm /etc/ssh/ssh_host_*"` will not be a solution here… because we are still using shell! :p

@mattwillsher, what is your opinion about it?

**Comment by mattwillsher** [comment]
Yes, I think find with register and then file would be succinct and suitable.

Another option is to look at the host keys var (sshd_defaults.HostKey) in role and use that. It's unlikely (though possible...) some one would override that value, as the intention is that that var holds the keys used by the given OS variant. To make it entirely generic I don't believe is possible - for example, ssh will no doubt introduce new parameters which will have to be encoded as defaults and also in the sshd template.

**Comment by johanfleury** [comment]
Hi.

The find module is not available before ansible version 2.

I propose to use `command: find /etc/ssh -iname "ssh_host_*"` until ansible 2 is out and globally used.

If that's ok for you, i'll push my changes.

**Comment by mattwillsher** [comment]
@johanfleury My preference is to use sshd_defaults.HostKey I think

**Comment by tterranigma** [comment]
@mattwillsher why was this marked as `wontfix`?

**Comment by jdnrg** [comment]
on amazonlinux2 validation fails due to missing hostkeys
```
TASK [willshersystems.sshd : Configuration] ************************************
fatal: [localhost]: FAILED! => {"changed": false, "checksum": "cb5869e74644dc696113badb660738991e077baa", "exit_status": 1, "msg": "failed to validate", "stderr": "Could not load host key: /etc/ssh/ssh_host_rsa_key\r\nCould not load host key: /etc/ssh/ssh_host_dsa_key\r\nCould not load host key: /etc/ssh/ssh_host_ecdsa_key\r\nCould not load host key: /etc/ssh/ssh_host_ed25519_key\r\nsshd: no hostkeys available -- exiting.\r\n", "stderr_lines": ["Could not load host key: /etc/ssh/ssh_host_rsa_key", "Could not load host key: /etc/ssh/ssh_host_dsa_key", "Could not load host key: /etc/ssh/ssh_host_ecdsa_key", "Could not load host key: /etc/ssh/ssh_host_ed25519_key", "sshd: no hostkeys available -- exiting."], "stdout": "", "stdout_lines": []}
```

**Pull request closed without merging**
