### PR TITLE
Adds ability to install a systemd service

### PR DESCRIPTION
**Pull request by tterranigma**
This PR is the result of me trying to solve #80 . The issue with the existing role is that if you want to install a second sshd service, it is not possible due to the variable `sshd_service` being "hardcoded". What happens is that when the OS-specific vars/ file is included, any custom value for that variable is overwritten. Also, it is not possible to use Match rules for everything as the directives supported there are limited (for instance the `Port` directive is not valid there and this is what I mainly wanted).

In this PR, I tried to solve this issue by adding an 'override' logic. If the user sets any of the vars/ variables they do not get overwritten by those under vars/. 

Also, this PR adds some templates for the sshd systemd service. I took them from Ubuntu 18.04 and simplified them. 

With this PR, I am now able to control 2 different sshd instances on my server, running on different ports.

I had only edited `Debian.yml` and `Ubuntu_18.yml`. If you agree with this PR, I will go the extra mile and edit the rest under vars/.

### CODE REVIEW

**Comment by mattwillsher** [comment]
I'm generally in favour of this change as it makes the role more flexible.

It obviously needs to pass the build tests.

**Comment by tterranigma** [comment]
I updated the rest of the vars/ files.

**Comment by mattwillsher** [comment]
Thanks for that - can you also update the README to reflect this new functionality?

**Comment by mattwillsher** [comment]
That's great, thanks. I'll get a new release out soon.

**Comment by Jakuje** [comment]
@nkakouros Hi, can you clarify what was the reason you added the set_facts part (ideally with some example playbook)? This makes this role pretty much unusable if invoked multiple times from a single playbook as the facts are global and their scope goes out of the first role invocation into the next one, making it impossible to use the role to create different included drop-in files or configuring more sshd services.

From my understanding, Ansible has (at least today) quite a nice variable precedence table and this role is following that so I do not see a reason why it would be a problem to override some of the system defaults.

I submitted a PR to remove these because of the reasons given above, but before doing so I would be interested why it was added in the first place. The commit message is not very descriptive.

https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

**Pull request merged**
