### PR TITLE
Addition notes about secondary variables

### PR DESCRIPTION
**Pull request by mattwillsher**
Add clarification from #170 to README

### CODE REVIEW

**Comment by mattwillsher** [comment]
I'll use this to also fix the linting.

**Comment by mattwillsher** [comment]
Why ignore them? A separate change is worth adding for them perhaps, and bump the minimum version?

**Comment by mattwillsher** [comment]
I think that schema error was because name was missing from the meta/main.yml file. First batch of linting issues have been updated, will finish soon.

**Comment by Jakuje** [comment]
Thanks for having a look into that. I think the centos6 ansible version is too old it does not support fqcn so it will probably require a bit more pre-processing as we already have for other missing features:

https://github.com/willshersystems/ansible-sshd/blob/master/.github/workflows/ansible-centos-check.yml#L11

I would just do something like `sed -i -e 's/ansible.builtin.//g/' */*.yml `

We can also remove the fqcn exception from 

https://github.com/willshersystems/ansible-sshd/blob/master/.ansible-lint#L4

**Comment by mattwillsher** [comment]
CentOS/EL 6 has been EOL for some time now. Should we continue to support it at all?

**Comment by Jakuje** [comment]
> CentOS/EL 6 has been EOL for some time now. Should we continue to support it at all?

CentOS 6 is EOL, but RHEL6 is still in Extended life cycle support (ELS) for at least two years:

https://access.redhat.com/support/policy/updates/errata#Life_Cycle_Dates

We do not support running the ansible controller on RHEL6, but we still want to support users who want to control the legacy nodes. Ideally, we should test the ansible from supported container to centos6, but that does not look like possible with the current github action so I started with the patching which should bring no functional difference.

**Comment by mattwillsher** [comment]
Change is ready for review.

**Review by Jakuje — APPROVED** [review]
looks good. Thanks!

**Pull request merged**
