### PR TITLE
fix: CI failure

### PR DESCRIPTION
**Pull request by mattwillsher**
Enhancement:

Reason:

Result:

Issue Tracker Tickets (Jira or BZ if any):

### CODE REVIEW

**Comment by Jakuje** [comment]
The Ubuntu is now broken (https://github.com/roles-ansible/check-ansible-ubuntu-latest-action/issues/4) but fedora test should be fixed with:
```
diff --git a/tests/tests_all_options.yml b/tests/tests_all_options.yml
index d085c09..f2be4e6 100644
--- a/tests/tests_all_options.yml
+++ b/tests/tests_all_options.yml
@@ -93,7 +93,7 @@
           | grep -o '^\(     \|       \)[A-Z][A-Za-z0-9]*\(.\|  \)' \
           | grep -v "[A-Za-z0-9] $" | grep -v "[^A-Za-z0-9 ]$" \
           | awk '{ print $1 }' \
-          | grep -v '^$' | grep -v "^\(Match\|OpenSSH\|The\|Arguments\|Theo\)$"
+          | grep -v '^$' | grep -v "^\(Match\|OpenSSH\|The\|Arguments\|Theo\|Tatu\)$"
       args:
         executable: /bin/bash
       register: sshd_options
```

**Comment by mattwillsher** [comment]
> The Ubuntu is now broken ([roles-ansible/check-ansible-ubuntu-latest-action#4](https://github.com/roles-ansible/check-ansible-ubuntu-latest-action/issues/4)) but fedora test should be fixed with:
> ...

Fedora fix incorporated, thanks @Jakuje 

I've raised a PR https://github.com/roles-ansible/check-ansible-ubuntu-latest-action/pull/5 for the Ubuntu issue.

**Comment by Jakuje** [comment]
> I've raised a PR [roles-ansible/check-ansible-ubuntu-latest-action#5](https://github.com/roles-ansible/check-ansible-ubuntu-latest-action/pull/5) for the Ubuntu issue.

Thanks! You can test it works by changing the path to the action in the workflow file to your fork by replacing `roles-ansible` with `mattwillsher` here:

https://github.com/willshersystems/ansible-sshd/blob/7c76e9d6ce66d7a0d3e06a2795c35889c33ddc73/.github/workflows/ansible-ubuntu.yml#L14

but I do not expect any issues.

**Comment by Jakuje** [comment]
I was too fast. We obviously do not have Ubuntu 24 definition in https://github.com/willshersystems/ansible-sshd/tree/main/vars -- I assume just copy of the 22 version should give us some results.

**Comment by mattwillsher** [comment]
Closing in favour of #289

**Pull request closed without merging**
