### PR TITLE
UsePrivilegeSeparation is deprecated since 2017/OpenSSH 7.5 - https:/…

### PR DESCRIPTION
**Pull request by thalunil**
…/www.openssh.com/txt/release-7.5

### CODE REVIEW

**Comment by Jakuje** [comment]
Looks good for current suse. Are there still some supported SUSE versions running some older OpenSSH version?

**Comment by thalunil** [comment]
According to https://en.opensuse.org/Lifetime
the current release is 15.2.
15.1 is supported until end of January 2021 (~ 4 weeks).

i would consider this makes sense for all current variants of SUSE.

**Comment by thalunil** [comment]
Repository for 15.1:
http://download.opensuse.org/distribution/leap/15.1/repo/oss/x86_64/

OpenSSH is 
http://download.opensuse.org/distribution/leap/15.1/repo/oss/x86_64/openssh-7.9p1-lp151.3.4.x86_64.rpm

So even this old 15.1 release is a more modern version.

please accept this PR.

**Review by Jakuje — APPROVED** [review]

**Comment by Jakuje** [comment]
Thank you! Merged.

**Pull request merged**
