### PR TITLE
test against multiple distros

### PR DESCRIPTION
**Pull request by chrismeyersfsu**
Use Docker in TravisCI to test multiple supported distros.

### CODE REVIEW

**Comment by mattwillsher** [comment]
Thanks for this, it's great to test against more operating systems. Interesting approach too.

I recall an issue with /var/run/sshd not existing inside Docker containers, hence the addition of /var/run/sshd management in this role. With the init system inside the containers, is this an issue? It looks like sshd might not be getting started during testing?

Looking at the output of the most recent run, sshd doesn't appear to be getting reloaded at the end despite changes to the sshd_config file. Is this an artefact of running inside Docker? The validation check looks to be passing though. 

I've added the -D option to the full run so, with a bit of luck, deltas for the config changes during testing can be seen.

**Comment by chrismeyersfsu** [comment]
Thanks for the background info. A little background for you. The Docker containers that these tests against come with the init system shoved back in them and ssh running. Maybe I need to remove ssh.

I'll try running these tests locally and see how the role is interacting with the `sshd_manage_service` variable.

**Comment by mattwillsher** [comment]
Good spot on sshd_managed_service. 

I recall having quite a bit of fuss with Docker at the time. `sshd_manage_service` and `sshd_manage_var_run` are a result. A few issues have been raised especially around `sshd_manage_var_run`, for example the currently open #43.

Do you have links to the container Dockerfiles? I had a look on Docker Hub but couldn't see the file or links to the RCS repository.

There are a couple of issues - #42 and #43 - that are related to Docker and testing that'd it'd be good to put to bed.

**Comment by chrismeyersfsu** [comment]
Dockerfiles are here https://github.com/chrismeyersfsu/provision_docker/tree/master/files

**Comment by mattwillsher** [comment]
Just to say I've not forgotten about this. Will get to work on it in the new year.

**Comment by mattwillsher** [comment]
Two New Years past :( 

It's going to happen I'm afraid.

**Pull request closed without merging**
