### PR TITLE
Add support for RHEL 9 and adjust tests for it

### PR DESCRIPTION
**Pull request by Jakuje**
This adds a proper support for RHEL9 (based on latest Fedora) and adjusts test for that.

### CODE REVIEW

**Comment by Jakuje** [comment]
@mattwillsher The travis-ci is no longer working, but it is still listed here as a required check preventing merging. I think you need to remove it somewhere in settings? We can then remove also the `.travis.yml`

@richm @nhosoi I would like to ask you for your review here.

**Review by nhosoi — APPROVED** [review]
lgtm
Thanks for the quick fix, @Jakuje!

**Comment by mattwillsher** [comment]
@Jakuje I've removed travis from the required checks.

**Review by mattwillsher — APPROVED** [review]

**Comment by Jakuje** [comment]
Thanks!

**Pull request merged**
