### PR TITLE
docs(changelog): version v0.24.1 [citest skip]

### PR DESCRIPTION
**Pull request by richm**
Update changelog and .README.html for version v0.24.1

Signed-off-by: Rich Megginson <rmeggins@redhat.com>

### CODE REVIEW

**Comment by mattwillsher** [comment]
Please fix the tests before release.

**Comment by Jakuje** [comment]
> Please fix the tests before release.

There is a fix for the centos7 in roles-ansible/check-ansible-centos-centos7-action#2 waiting to get merged. We can use my fork for the time being, but the maintainer was usually responsive to PRs.

**Comment by mattwillsher** [comment]
Either is fine - we should not merge with failed tests. If we use your branch @Jakuje, please raise an issue or PR to revert once upstream is fixed. Failed test for a CentOS version on a CentOS related release looks bad, particularly being so visible. 
Being picky I'd say this is a feature release not a fix, but that's not a blocker.

**Review by Jakuje — APPROVED** [review]
CI on CentOS 7 is fixed. The change to the action is merged so ack.

**Pull request merged**
