### PR TITLE
Adding support for RedHat8/CentOS8.

### PR DESCRIPTION
**Pull request by bengoa**
Adding support for RedHat8/CentOS8.

Dropping deprecated option `UsePrivilegeSeparation`.

### CODE REVIEW

**Comment by dev-zero** [comment]
on my fresh CentOS8 (minimal) installation, I have: `GSSAPICleanupCredentials no`

**Comment by bengoa** [comment]
Hello,

On a fresh CentOS7 (minimal) installation you'll have `GSSAPICleanupCredentials no` as well, but this role is changing it to `yes`.

I tried to keep the same behaviour, dropping only the deprecated option, but I can change it and update here if you prefer.

**Comment by dev-zero** [comment]
unless there's a good reason to diverge from the distro defaults (like the `PermitRootLogin`) I usually prefer to keep them. Since here you're adding new support for CentOS/RedHat 8, this might be a good point to bring the ansible-sshd configuration in line with the distro defaults.

**Comment by bengoa** [comment]
All right, I agree with you. I'll push an update soon.

**Comment by mattwillsher** [comment]
I took #97 over this. Thanks for you contribution.

**Pull request closed without merging**
