### PR TITLE
release 0.18.1

### PR DESCRIPTION
**Pull request by Jakuje**
This is a draft for the next release.

### CODE REVIEW

**Comment by Jakuje** [comment]
@mattwillsher I put together a draft for the next release (I decided for minor as there is really no huge amount of changes, but I can change to 0.19.0 if you prefer.

**Review by mattwillsher — APPROVED** [review]

**Comment by mattwillsher** [comment]
@Jakuje lgtm, thank you.

**Review by mattwillsher — APPROVED** [review]

**Comment by richm** [comment]
> @richm do you have some other plans except for #215 that should go in before the release?

No.

**Comment by Jakuje** [comment]
@mattwillsher merged. I think the galaxy update is still a manual thing?

**Comment by mattwillsher** [comment]
Done - v0.18.1 is available on Galaxy

**Pull request merged**
