### PR TITLE
Updates syntax to Ansible 2.7 era

### PR DESCRIPTION
**Pull request by nkakouros**
As ansible 2.7 is not out yet, if you are interested in this PR, maybe it should be accepted [after 2.7 is out](https://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_7.html).

### CODE REVIEW

**Comment by tterranigma** [comment]
The failure is valid, I have [asked](https://github.com/ansible/ansible/issues/18430) on the ansible project on how to combine the new `loop` keyword with `first_found`.

**Comment by mattwillsher** [comment]
The role should work on as many versions as reasonably possible, although the test is done against the current version of the ansible ppa.

At least, a few months should pass before mandating 2.7 as a minimal version.

**Comment by tterranigma** [comment]
In that case, this should be put on hold until the `with_` is removed (I couldn't find a target release when this will happen). Should we close this now and retry then?

**Comment by mattwillsher** [comment]
It can be left open, it's a good reminder.

**Comment by tterranigma** [comment]
Now that 2.8 is out, I think it would be a good idea to merge this. Since the deprecation cycle in ansible is 4 minor versions long, the oldest "officially" supported version is 2.5 now. The changes in this PR, I think should be compatible with at as old a version as 2.5.

**Comment by mattwillsher** [comment]
Merged, thanks. Will release with v0.8.0 shortly.

**Pull request merged**
