### PR TITLE
Drop support for Ansible 2.8 by bumping the Ansible version to 2.9

### PR DESCRIPTION
**Pull request by spetrosi**
Bug 1989197 - drop support for Ansible 2.8
https://bugzilla.redhat.com/show_bug.cgi?id=1989197

### CODE REVIEW

**Comment by Jakuje** [comment]
we just recently bumpted the minimum ansible version to 2.8 in (#127), but I am not sure if we need to support 2.8 anymore. @mattwillsher what do you think?

**Comment by mattwillsher** [comment]
I don't see the need to drop support unless there is functionality we require that 2.8 doesn't support.

**Comment by spetrosi** [comment]
@mattwillsher [linux-system-roles](https://github.com/linux-system-roles) decided to drop support for Ansible 2.8 because it reached its EOL on January 21, 2021, and some roles faced some errors related to 2.8 version. Hence, linux-system-roles remove tests for Ansible 2.8 from the CI, meaning that there is no guarantee that roles work on Ansible 2.8. Even though some roles might work on Ansible 2.8, keeping the support for a version that is EOL is too much effort with less usefulness.

**Comment by mattwillsher** [comment]
Ok, I'm happy to go with the consensus on this if that's the community standard.

**Comment by mattwillsher** [comment]
It's arguable that min rev is really 2.10 #138 

I'll try to spend a bit of time tidying this up generally. 

I don't see an immediate need disbar 2.8,  and it's a good chance to do house keeping and properly have a tested minimum version.

**Comment by spetrosi** [comment]
@mattwillsher Can we merge this PR?

**Comment by mattwillsher** [comment]
Yes it will be merged, but I want to get a release out for CentOS 6 and possible Debian 11 before this goes in.

**Pull request merged**
