### PR TITLE
Remove deprecated options

### PR DESCRIPTION
**Pull request by mfredholm**
Remove deprecated SSH protocol 1 options
(https://salsa.debian.org/ssh-team/openssh/commit/fb87db8aa47d3508be8e5bb1d21897fa1f2eca90)

### CODE REVIEW

**Comment by mattwillsher** [comment]
Checking an Ubuntu cloud image for 18.04 the only values that are set by default are:

```
PasswordAuthentication no
ChallengeResponseAuthentication no
UsePAM yes
X11Forwarding yes
PrintMotd no
AcceptEnv LANG LC_*
Subsystem	sftp	/usr/lib/openssh/sftp-server
```

If this is correct for other installation types, these should be the only defaults set in ubuntu_18.yml

What do you think?

**Comment by mfredholm** [comment]
Hi Matt, sounds good!

**Comment by mfredholm** [comment]
Will this be merged some time soon?

**Comment by mattwillsher** [comment]
Yes, sorry for the delay, thanks for prompting. New galaxy release also.

**Pull request merged**
