### PR TITLE
Add check for non-inclusive language; Clean up / Workaround non-inclusive words

### PR DESCRIPTION
**Pull request by nhosoi**
Add check for non-inclusive language
    
Add a check for usage of terms and language that is considered non-inclusive. We are using the woke tool for this with a wordlist that can be found at
https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/config_files/woke.yml

Clean up / Workaround non-inclusive words
- CHANGELOG.md
- tests/tests_include_present.yml

### CODE REVIEW

**Review by richm — APPROVED** [review]
lgtm

**Comment by Jakuje** [comment]
@mattwillsher maybe this would make sense to go in before the release. Can you have a look if it makes sense to you?

**Comment by mattwillsher** [comment]
@Jakuje I agree - I did try to merge it earlier from my phone app but it doesn't have workflow permissions.  Please go ahead and merge and include in the release.

**Comment by Jakuje** [comment]
Thanks! Merging.

**Pull request merged**
