### PR TITLE
docs(changelog): version v0.21.0 [citest skip]

### PR DESCRIPTION
**Pull request by spetrosi**
Update changelog and .README.html for version v0.21.0

### CODE REVIEW

**Comment by spetrosi** [comment]
@mattwillsher opening this instead of  #251 to add recent commits and .README.html. We use .README.html when building RPM. We used to convert md>html during the build, but the build environment has limited packages, it became hard to properly convert into a pretty HTML there.

**Comment by mattwillsher** [comment]
How was the .README.html generated @spetrosi ?

**Comment by spetrosi** [comment]
> How was the .README.html generated @spetrosi ?

The release script gets README.html from origin/docs:latest/README.html, see https://github.com/linux-system-roles/auto-maintenance/blob/main/role-make-version-changelog.sh#L309C18-L309C18
And README in the docs branch is generated by https://github.com/willshersystems/ansible-sshd/blob/main/.github/workflows/build_docs.yml

**Comment by mattwillsher** [comment]
We need a doc detailing the process here if it's more that just updating the CHANGELOG.md. 

I'm unclear why .README.html shows in this single commit if it was generated by some other script. 

The process needs to be straight forward for any one who is doing a release.

**Comment by spetrosi** [comment]
I agree, it's complicated now, I'll add documentation to auto-maintenance repo. I had an idea to create a github action that anyone can run ad hoc to create a new release but didn't get to it yet.
To your question, the latest/README.html from docs branch is copied to the main branch `.README.html` so that we can get it in RPM spec during build without the need to pull one more source, which would need to be the docs branch in addition to the main branch for each repo.
And the script copies to a  hidden .README.html because it would get outdated between the releases when new changes to README.md are done. So this hidden .README.hml should not be used actually.

**Comment by mattwillsher** [comment]
@spetrosi - please add the steps as a list of commands and manual steps, runbook style, to the README.md in a new section near the end of the document. I would like to ensure releases are consistent regardless of who is performing the release.

**Comment by spetrosi** [comment]
I've added a contributing.md file to keep README.md targeted to end-users only. Does this work?

**Comment by mattwillsher** [comment]
Brilliant, thats even better, thank you @spetrosi

**Review by mattwillsher — APPROVED** [review]

**Comment by mattwillsher** [comment]
This is now released - the old role in galaxy needed to be deleted due to the change in name of the default branch.

**Pull request merged**
